import type { ProcessFlow, ProcessFlowEdge, ProcessFlowNode } from "./processFlow";

export const PDF_ENTITY_TO_HASH: Record<string, string[]> = {
  "Cana Moída (KPI)": ["H30", "H36", "H167", "H168", "H169"],
  "Tempo & Dias (KPI strip)": ["H160", "H161", "H162", "H163", "H164"],
  "Consumo Total de Vapor (KPI)": ["H568", "H586", "H587", "H591", "H592"],
  "Produção de Vapor por kg Bagaço — Safra": ["H558", "H567"],
  "Estoque Inicial": [],
  "Bagaço da Cana": ["H536", "H540", "H541", "H542"],
  "Bagaço Total Disponível": ["H545", "H681"],
  "Consumo Bagaço — Moagem de Cana": ["H546", "H547", "H682", "H683"],
  "Consumo Bagaço — Filtro Rotativo": [],
  "Consumo Bagaço — Partidas e Paradas": ["H544", "H680"],
  "Consumo Total de Bagaço": ["H679"],
  "Bagaço Reservado Próxima Safra": ["H684"],
  "Sobra de Bagaço": ["H548", "H684", "H685"],
};

const COL_X = { L: 60, C1: 460, C2: 880, R: 1300 } as const;

const nodes: ProcessFlowNode[] = [
  {
    id: "estoque_inicial",
    kind: "io",
    title: "Estoque Inicial",
    subtitle: "Bagaço carry-over",
    position: { x: COL_X.L, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Estoque Inicial"],
  },
  {
    id: "cana_moida_kpi",
    kind: "io",
    title: "Cana Moída",
    subtitle: "KPI · Plano safra",
    position: { x: COL_X.C1, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Cana Moída (KPI)"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "vapor_kpi",
    kind: "io",
    title: "Consumo Total de Vapor",
    subtitle: "KPI · Vapor produzido + consumido",
    position: { x: COL_X.C2, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Consumo Total de Vapor (KPI)"],
    sourceDefinition: "PRODUÇÃO + CONSUMO DE VAPOR",
  },
  {
    id: "tempo_dias_safra",
    kind: "process",
    title: "Tempo & Dias de Safra",
    subtitle: "KPI · Plano safra",
    position: { x: COL_X.R, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Tempo & Dias (KPI strip)"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "bagaco_da_cana",
    kind: "process",
    title: "Bagaço da Cana",
    subtitle: "Fibra cana · Bagaço total t/h",
    position: { x: COL_X.L, y: 380 },
    fieldIds: PDF_ENTITY_TO_HASH["Bagaço da Cana"],
    sourceDefinition: "PRODUÇÃO E SOBRA DE BIOMASSA",
  },
  {
    id: "bagaco_total",
    kind: "hub",
    title: "Bagaço Total Disponível",
    subtitle: "HUB · t/h + ton (safra)",
    position: { x: COL_X.C1, y: 380 },
    fieldIds: PDF_ENTITY_TO_HASH["Bagaço Total Disponível"],
    sourceDefinition: "PRODUÇÃO E SOBRA DE BIOMASSA / CONSUMO BAGAÇO TOTAL",
  },
  {
    id: "moagem_cana_consumo",
    kind: "process",
    title: "Consumo Bagaço — Moagem",
    subtitle: "Caldeiras 21 + 42 kgf/cm²",
    position: { x: COL_X.C2, y: 380 },
    fieldIds: PDF_ENTITY_TO_HASH["Consumo Bagaço — Moagem de Cana"],
    sourceDefinition: "PRODUÇÃO + CONSUMO DE VAPOR / CONSUMO BAGAÇO TOTAL",
  },
  {
    id: "consumo_total",
    kind: "io",
    title: "Consumo Total de Bagaço",
    subtitle: "BAGAÇO TOTAL (ton)",
    position: { x: COL_X.R, y: 380 },
    fieldIds: PDF_ENTITY_TO_HASH["Consumo Total de Bagaço"],
    sourceDefinition: "CONSUMO BAGAÇO TOTAL",
  },
  {
    id: "vapor_kg_safra",
    kind: "io",
    title: "Vapor/kg Bagaço — Safra",
    subtitle: "Consumo Esp 21 / 42 (kgV/kgbag)",
    position: { x: COL_X.C1, y: 720 },
    fieldIds: PDF_ENTITY_TO_HASH["Produção de Vapor por kg Bagaço — Safra"],
    sourceDefinition: "PRODUÇÃO DE VAPOR",
  },
  {
    id: "filtro_rotativo",
    kind: "process",
    title: "Consumo Bagaço — Filtro Rotativo",
    subtitle: "Decoração",
    position: { x: COL_X.C2, y: 720 },
    fieldIds: PDF_ENTITY_TO_HASH["Consumo Bagaço — Filtro Rotativo"],
  },
  {
    id: "partidas_paradas",
    kind: "process",
    title: "Consumo Bagaço — Partidas e Paradas",
    subtitle: "Input % · t/h · ton",
    position: { x: COL_X.C2, y: 1060 },
    fieldIds: PDF_ENTITY_TO_HASH["Consumo Bagaço — Partidas e Paradas"],
    sourceDefinition: "PRODUÇÃO E SOBRA DE BIOMASSA / CONSUMO BAGAÇO TOTAL",
  },
  {
    id: "reserva_proxima",
    kind: "io",
    title: "Reserva Próxima Safra",
    subtitle: "Sobra biomassa acumulada (ton)",
    position: { x: COL_X.R, y: 720 },
    fieldIds: PDF_ENTITY_TO_HASH["Bagaço Reservado Próxima Safra"],
    sourceDefinition: "CONSUMO BAGAÇO TOTAL",
  },
  {
    id: "sobra_bagaco",
    kind: "io",
    title: "Sobra de Bagaço",
    subtitle: "t/h · ton acumulada / mensal",
    position: { x: COL_X.R, y: 1060 },
    fieldIds: PDF_ENTITY_TO_HASH["Sobra de Bagaço"],
    sourceDefinition: "PRODUÇÃO E SOBRA DE BIOMASSA / CONSUMO BAGAÇO TOTAL",
  },
];

const edges: ProcessFlowEdge[] = [
  { id: "b1", source: "estoque_inicial", target: "bagaco_total", label: "estoque" },
  { id: "b2", source: "bagaco_da_cana", target: "bagaco_total", label: "bagaço" },
  { id: "b3", source: "bagaco_total", target: "moagem_cana_consumo", label: "consumo" },
  { id: "b4", source: "bagaco_total", target: "filtro_rotativo", label: "consumo" },
  { id: "b5", source: "bagaco_total", target: "partidas_paradas", label: "consumo" },
  { id: "b6", source: "moagem_cana_consumo", target: "consumo_total" },
  { id: "b7", source: "filtro_rotativo", target: "consumo_total" },
  { id: "b8", source: "partidas_paradas", target: "consumo_total" },
  { id: "b9", source: "bagaco_total", target: "reserva_proxima", label: "reserva" },
  { id: "b10", source: "bagaco_total", target: "sobra_bagaco", label: "sobra" },
];

export const BAGACO_DASHBOARD_FLOW: ProcessFlow = { nodes, edges };

export const ZONE_ANCHOR_IDS = [
  "estoque_inicial",
  "bagaco_da_cana",
  "bagaco_total",
  "moagem_cana_consumo",
  "filtro_rotativo",
  "partidas_paradas",
  "consumo_total",
  "reserva_proxima",
  "sobra_bagaco",
] as const;
