import type { ProcessFlow, ProcessFlowEdge, ProcessFlowNode } from "./processFlow";

export const PDF_ENTITY_TO_HASH: Record<string, string[]> = {
  Cana: ["H5", "H8"],
  "Planejamento Moagem": ["H3", "H7", "H9"],
  "Composição Cana": ["H50", "H51", "H52", "H54"],
  "Dados Extração": ["H38", "H39", "H42", "H43"],
  'Moenda 1 - 66"': ["H77"],
  'Moenda 2 - 84"': ["H77"],
  "Caldo Primário 1": ["H77", "H66", "H68", "H69"],
  "Caldo Primário 2": ["H77", "H66", "H68", "H69"],
  "Caldo Secundário 1": ["H109", "H100", "H102", "H103"],
  "Caldo Secundário 2": ["H109", "H100", "H102", "H103"],
  "Bagaço 1": ["H92", "H86", "H87", "H89"],
  "Bagaço 2": ["H92", "H86", "H87", "H89"],
  "Caldo Misto": ["H149", "H136", "H138", "H139"],
  "Tanque Água de Embebição": ["H148", "H46"],
  Caldeiras: [],
  "Tanque de Condensados": [],
  "Tanque de Caldo Misto para Açúcar": [],
  "Tanque de Caldo Misto para Etanol": [],
  "Produção de Açúcar": [],
  "Produção de Etanol": [],
  "Água Lavagem Tela Filtro": [],
  "Água Limpeza de Peneiras (Moenda 1)": [],
  "Água Limpeza de Peneiras (Moenda 2)": [],
};

const nodes: ProcessFlowNode[] = [
  {
    id: "planejamento",
    kind: "process",
    title: "Planejamento Moagem",
    subtitle: "Capacidade nominal",
    position: { x: 60, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Planejamento Moagem"],
    sourceDefinition: "PLANEJAMENTO MOAGEM",
  },
  {
    id: "cana",
    kind: "io",
    title: "Cana",
    subtitle: "Matéria prima",
    position: { x: 60, y: 360 },
    fieldIds: PDF_ENTITY_TO_HASH["Cana"],
    sourceDefinition: "PLANEJAMENTO MOAGEM",
  },
  {
    id: "materia_prima",
    kind: "process",
    title: "Composição Cana",
    subtitle: "% mássico",
    position: { x: 60, y: 660 },
    fieldIds: PDF_ENTITY_TO_HASH["Composição Cana"],
    sourceDefinition: "COMPOSIÇÃO MATERIA PRIMA",
  },
  {
    id: "extracao",
    kind: "process",
    title: "Dados Extração",
    subtitle: "Eficiência",
    position: { x: 60, y: 960 },
    fieldIds: PDF_ENTITY_TO_HASH["Dados Extração"],
    sourceDefinition: "DADOS EXTRAÇÃO",
  },
  {
    id: "agua_peneiras_1",
    kind: "io",
    title: "Água Limpeza Peneiras 1",
    subtitle: "60,0 °C",
    position: { x: 380, y: 60 },
    fieldIds: [],
  },
  {
    id: "moenda1_66",
    kind: "hub",
    title: "Moenda 1",
    subtitle: '66" — MD-1',
    position: { x: 380, y: 360 },
    fieldIds: PDF_ENTITY_TO_HASH['Moenda 1 - 66"'],
    sourceDefinition: "COMPOSIÇÃO MÁSSICA DO CALDO 1° TERNO",
  },
  {
    id: "moenda2_84",
    kind: "hub",
    title: "Moenda 2",
    subtitle: '84" — MD-2',
    position: { x: 380, y: 960 },
    fieldIds: PDF_ENTITY_TO_HASH['Moenda 2 - 84"'],
    sourceDefinition: "COMPOSIÇÃO MÁSSICA DO CALDO 2° TERNO",
  },
  {
    id: "agua_peneiras_2",
    kind: "io",
    title: "Água Limpeza Peneiras 2",
    subtitle: "60,0 °C",
    position: { x: 380, y: 1260 },
    fieldIds: [],
  },
  {
    id: "caldo_primario_1",
    kind: "process",
    title: "Caldo Primário 1",
    subtitle: "Moenda 1",
    position: { x: 720, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Caldo Primário 1"],
    sourceDefinition: "COMPOSIÇÃO DO CALDO 1° TERNO",
  },
  {
    id: "caldo_secundario_1",
    kind: "process",
    title: "Caldo Secundário 1",
    subtitle: "Moenda 1",
    position: { x: 720, y: 360 },
    fieldIds: PDF_ENTITY_TO_HASH["Caldo Secundário 1"],
    sourceDefinition: "COMPOSIÇÃO DO CALDO 2° TERNO",
  },
  {
    id: "bagaco_1",
    kind: "process",
    title: "Bagaço 1",
    subtitle: "Moenda 1",
    position: { x: 720, y: 660 },
    fieldIds: PDF_ENTITY_TO_HASH["Bagaço 1"],
    sourceDefinition: "COMPOSIÇÃO MÁSSICA DO BAGAÇO 1° TERNO",
  },
  {
    id: "caldo_primario_2",
    kind: "process",
    title: "Caldo Primário 2",
    subtitle: "Moenda 2",
    position: { x: 720, y: 960 },
    fieldIds: PDF_ENTITY_TO_HASH["Caldo Primário 2"],
    sourceDefinition: "COMPOSIÇÃO DO CALDO 1° TERNO",
  },
  {
    id: "caldo_secundario_2",
    kind: "process",
    title: "Caldo Secundário 2",
    subtitle: "Moenda 2",
    position: { x: 720, y: 1260 },
    fieldIds: PDF_ENTITY_TO_HASH["Caldo Secundário 2"],
    sourceDefinition: "COMPOSIÇÃO DO CALDO 2° TERNO",
  },
  {
    id: "bagaco_2",
    kind: "process",
    title: "Bagaço 2",
    subtitle: "Moenda 2",
    position: { x: 720, y: 1560 },
    fieldIds: PDF_ENTITY_TO_HASH["Bagaço 2"],
    sourceDefinition: "COMPOSIÇÃO MÁSSICA DO BAGAÇO 1° TERNO",
  },
  {
    id: "caldeiras",
    kind: "hub",
    title: "Caldeiras",
    subtitle: "Bagaço → Vapor",
    position: { x: 1060, y: 60 },
    fieldIds: [],
  },
  {
    id: "tanque_embebicao",
    kind: "hub",
    title: "Tanque Água de Embebição",
    subtitle: "50,0 °C",
    position: { x: 1060, y: 360 },
    fieldIds: PDF_ENTITY_TO_HASH["Tanque Água de Embebição"],
    sourceDefinition: "DADOS EXTRAÇÃO",
  },
  {
    id: "tanque_condensados",
    kind: "hub",
    title: "Tanque de Condensados",
    subtitle: "30,0 °C",
    position: { x: 1060, y: 660 },
    fieldIds: [],
  },
  {
    id: "caldo_misto",
    kind: "io",
    title: "Caldo Misto",
    subtitle: "Convergência",
    position: { x: 1060, y: 960 },
    fieldIds: PDF_ENTITY_TO_HASH["Caldo Misto"],
    sourceDefinition: "COMPOSIÇÃO DO CALDO MISTO",
  },
  {
    id: "agua_lavagem",
    kind: "io",
    title: "Água Lavagem Tela Filtro",
    subtitle: "50,0 °C",
    position: { x: 1060, y: 1260 },
    fieldIds: [],
  },
  {
    id: "tanque_misto_acucar",
    kind: "hub",
    title: "Tanque de Caldo Misto para Açúcar",
    subtitle: "60,0 °C",
    position: { x: 1380, y: 960 },
    fieldIds: [],
  },
  {
    id: "tanque_misto_etanol",
    kind: "hub",
    title: "Tanque de Caldo Misto para Etanol",
    subtitle: "60,0 °C",
    position: { x: 1380, y: 1260 },
    fieldIds: [],
  },
  {
    id: "producao_acucar",
    kind: "io",
    title: "Produção de Açúcar",
    subtitle: "Destino",
    position: { x: 1700, y: 960 },
    fieldIds: [],
  },
  {
    id: "producao_etanol",
    kind: "io",
    title: "Produção de Etanol",
    subtitle: "Destino",
    position: { x: 1700, y: 1260 },
    fieldIds: [],
  },
];

const edges: ProcessFlowEdge[] = [
  { id: "e1", source: "cana", target: "moenda1_66", label: "cana" },
  { id: "e2", source: "cana", target: "moenda2_84", label: "cana" },
  { id: "e3", source: "planejamento", target: "moenda1_66" },
  { id: "e4", source: "materia_prima", target: "moenda1_66" },
  { id: "e5", source: "extracao", target: "moenda2_84" },
  { id: "e6", source: "tanque_embebicao", target: "moenda1_66", label: "água embebição" },
  { id: "e7", source: "tanque_embebicao", target: "moenda2_84", label: "água embebição" },
  { id: "e8", source: "agua_peneiras_1", target: "moenda1_66", label: "limpeza" },
  { id: "e9", source: "agua_peneiras_2", target: "moenda2_84", label: "limpeza" },
  { id: "e10", source: "moenda1_66", target: "caldo_primario_1", label: "caldo primário" },
  { id: "e11", source: "moenda1_66", target: "caldo_secundario_1", label: "caldo secundário" },
  { id: "e12", source: "moenda1_66", target: "bagaco_1", label: "bagaço" },
  { id: "e13", source: "moenda2_84", target: "caldo_primario_2", label: "caldo primário" },
  { id: "e14", source: "moenda2_84", target: "caldo_secundario_2", label: "caldo secundário" },
  { id: "e15", source: "moenda2_84", target: "bagaco_2", label: "bagaço" },
  { id: "e16", source: "bagaco_1", target: "caldeiras", label: "bagaço" },
  { id: "e17", source: "bagaco_2", target: "caldeiras", label: "bagaço" },
  { id: "e18", source: "tanque_condensados", target: "tanque_embebicao", label: "condensado" },
  { id: "e19", source: "caldo_primario_1", target: "caldo_misto" },
  { id: "e20", source: "caldo_secundario_1", target: "caldo_misto" },
  { id: "e21", source: "caldo_primario_2", target: "caldo_misto" },
  { id: "e22", source: "caldo_secundario_2", target: "caldo_misto" },
  { id: "e23", source: "agua_lavagem", target: "caldo_misto", label: "lavagem" },
  { id: "e24", source: "caldo_misto", target: "tanque_misto_acucar", label: "açúcar" },
  { id: "e25", source: "caldo_misto", target: "tanque_misto_etanol", label: "etanol" },
  { id: "e26", source: "tanque_misto_acucar", target: "producao_acucar" },
  { id: "e27", source: "tanque_misto_etanol", target: "producao_etanol" },
];

export const MOAGEM_PHYSICAL_FLOW: ProcessFlow = { nodes, edges };
