import type { ProcessFlow, ProcessFlowEdge, ProcessFlowNode } from "./processFlow";

export const PDF_ENTITY_TO_HASH: Record<string, string[]> = {
  "Qualidade da Cana": ["H51", "H53", "H52", "H54", "H55", "H181"],
  "Moagem de Cana": ["H36", "H30", "H166", "H167", "H172", "H173"],
  "Moagem Taxa": ["H5", "H7", "H28", "H29", "H42", "H45"],
  Regeneradores: [],
  "Aquecedores de Caldo": ["H348", "H350", "H351", "H352", "H353", "H355"],
  "Vapor Açúcar": [],
  "Vapor Destilaria": ["H863", "H853", "H854", "H855"],
  "Fábrica de Açúcar": ["H216", "H210", "H336", "H231", "H197", "H253"],
  "Produção de Etanol": ["H218", "H217", "H219", "H214", "H232", "H256"],
  "Produção de Levedura": ["H690", "H691", "H692"],
  "Eficiências Assumidas": ["H284", "H285", "H286", "H287", "H288", "H289"],
  "Eficiências Calculadas": ["H221", "H222", "H223", "H224", "H225", "H239"],
  Rendimentos: ["H226", "H227", "H228", "H229", "H230"],
  Vapor: ["H568", "H550", "H559", "H586", "H587"],
  Bagaço: ["H92", "H125", "H679", "H681", "H684", "H548"],
  "Energia Safra": ["H243", "H245", "H247", "H248", "H249"],
  "Energia Operacional": ["H244", "H246", "H250", "H251", "H254", "H260"],
};

const COL_X = { L: 60, C1: 460, C2: 880, R: 1300 } as const;

const nodes: ProcessFlowNode[] = [
  {
    id: "qualidade_cana",
    kind: "io",
    title: "Qualidade da Cana",
    subtitle: "01 · Composição",
    position: { x: COL_X.L, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Qualidade da Cana"],
    sourceDefinition: "COMPOSIÇÃO MATERIA PRIMA",
  },
  {
    id: "moagem_cana",
    kind: "process",
    title: "Moagem de Cana",
    subtitle: "02 · Plano safra",
    position: { x: COL_X.L, y: 420 },
    fieldIds: PDF_ENTITY_TO_HASH["Moagem de Cana"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "moagem_taxa",
    kind: "process",
    title: "Moagem — Taxa & Extração",
    subtitle: "02 · Moendas · Embebição",
    position: { x: COL_X.L, y: 800 },
    fieldIds: PDF_ENTITY_TO_HASH["Moagem Taxa"],
    sourceDefinition: "PLANEJAMENTO MOAGEM / DADOS EXTRAÇÃO",
  },
  {
    id: "regeneradores",
    kind: "process",
    title: "Regeneradores",
    subtitle: "03 · Caldo × Vinhaça / Caldo × Caldo",
    position: { x: COL_X.L, y: 1180 },
    fieldIds: PDF_ENTITY_TO_HASH["Regeneradores"],
  },
  {
    id: "aquecedores_caldo",
    kind: "process",
    title: "Aquecedores de Caldo",
    subtitle: "04 · V1 · V2 · V3",
    position: { x: COL_X.L, y: 1500 },
    fieldIds: PDF_ENTITY_TO_HASH["Aquecedores de Caldo"],
    sourceDefinition: "AQUECIMENTO - TIPO VAPOR",
  },
  {
    id: "vapor_acucar",
    kind: "process",
    title: "Tipo de Vapor — Açúcar",
    subtitle: "05 · Vácuos A · B · Granagem",
    position: { x: COL_X.C1, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Vapor Açúcar"],
  },
  {
    id: "vapor_destilaria",
    kind: "process",
    title: "Tipo de Vapor — Destilaria",
    subtitle: "06 · Coluna A · B · Desidratação",
    position: { x: COL_X.C1, y: 420 },
    fieldIds: PDF_ENTITY_TO_HASH["Vapor Destilaria"],
    sourceDefinition: "CALCULO APARELHOS HIDRATADO - PREMISSA",
  },
  {
    id: "vapor",
    kind: "process",
    title: "Vapor",
    subtitle: "11 · Caldeiras 21 / 42 kgf/cm²",
    position: { x: COL_X.C1, y: 800 },
    fieldIds: PDF_ENTITY_TO_HASH["Vapor"],
    sourceDefinition: "PRODUÇÃO DE VAPOR / CONSUMO DE VAPOR",
  },
  {
    id: "bagaco",
    kind: "process",
    title: "Bagaço",
    subtitle: "12 · Vazão · Consumo · Sobra",
    position: { x: COL_X.C1, y: 1180 },
    fieldIds: PDF_ENTITY_TO_HASH["Bagaço"],
    sourceDefinition: "COMPOSIÇÃO BAGAÇO / CONSUMO BAGAÇO TOTAL",
  },
  {
    id: "fabrica_acucar",
    kind: "io",
    title: "Fábrica de Açúcar",
    subtitle: "07 · Produção açúcar",
    position: { x: COL_X.C2, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Fábrica de Açúcar"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "producao_etanol",
    kind: "io",
    title: "Produção de Etanol",
    subtitle: "08 · Hidratado · Anidro",
    position: { x: COL_X.C2, y: 460 },
    fieldIds: PDF_ENTITY_TO_HASH["Produção de Etanol"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "producao_levedura",
    kind: "io",
    title: "Produção de Levedura",
    subtitle: "09 · kg/dia · kg/mês",
    position: { x: COL_X.C2, y: 860 },
    fieldIds: PDF_ENTITY_TO_HASH["Produção de Levedura"],
    sourceDefinition: "CALCULO DE PRODUÇÃO DA LEVEDURA",
  },
  {
    id: "eficiencias_assumido",
    kind: "process",
    title: "Eficiências — Assumidas",
    subtitle: "10 · PREMISSA · Rendimento",
    position: { x: COL_X.C2, y: 1180 },
    fieldIds: PDF_ENTITY_TO_HASH["Eficiências Assumidas"],
    sourceDefinition: "RENDIMENTO",
  },
  {
    id: "eficiencias_calculado",
    kind: "process",
    title: "Eficiências — Calculadas",
    subtitle: "10 · INFO GERAIS · Plano safra",
    position: { x: COL_X.C2, y: 1560 },
    fieldIds: PDF_ENTITY_TO_HASH["Eficiências Calculadas"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "rendimentos",
    kind: "process",
    title: "Rendimentos consolidados",
    subtitle: "10 · RGD · RTC · RIT STAB",
    position: { x: COL_X.R, y: 60 },
    fieldIds: PDF_ENTITY_TO_HASH["Rendimentos"],
    sourceDefinition: "PLANO SAFRA / RENDIMENTO",
  },
  {
    id: "eficiencias",
    kind: "io",
    title: "Eficiências",
    subtitle: "10 · Anchor · ver pareadas",
    position: { x: COL_X.R, y: 440 },
    fieldIds: ["H290"],
    sourceDefinition: "RENDIMENTO",
  },
  {
    id: "energia_eletrica",
    kind: "process",
    title: "Energia — Safra",
    subtitle: "13 · Produção · Exportação",
    position: { x: COL_X.R, y: 760 },
    fieldIds: PDF_ENTITY_TO_HASH["Energia Safra"],
    sourceDefinition: "PLANO SAFRA",
  },
  {
    id: "energia_operacional",
    kind: "process",
    title: "Energia — Operacional",
    subtitle: "13 · Diária · Aproveitamento · TCH",
    position: { x: COL_X.R, y: 1120 },
    fieldIds: PDF_ENTITY_TO_HASH["Energia Operacional"],
    sourceDefinition: "PLANO SAFRA / PREMISSA / INFO COMPLEMENTARES",
  },
];

const edges: ProcessFlowEdge[] = [
  { id: "p1", source: "moagem_cana", target: "qualidade_cana", label: "matéria prima" },
  { id: "p2", source: "moagem_cana", target: "moagem_taxa" },
  { id: "p3", source: "bagaco", target: "vapor", label: "bagaço" },
  { id: "p4", source: "vapor", target: "vapor_acucar", label: "vapor" },
  { id: "p5", source: "vapor", target: "vapor_destilaria", label: "vapor" },
  { id: "p6", source: "vapor", target: "energia_eletrica", label: "vapor" },
  { id: "p7", source: "vapor_acucar", target: "fabrica_acucar" },
  { id: "p8", source: "vapor_destilaria", target: "producao_etanol" },
  { id: "p9", source: "aquecedores_caldo", target: "fabrica_acucar" },
  { id: "p10", source: "fabrica_acucar", target: "eficiencias" },
  { id: "p11", source: "producao_etanol", target: "eficiencias" },
  { id: "p12", source: "eficiencias_assumido", target: "rendimentos" },
  { id: "p13", source: "eficiencias_calculado", target: "rendimentos" },
  { id: "p14", source: "energia_eletrica", target: "energia_operacional" },
];

export const PREMISSAS_DASHBOARD_FLOW: ProcessFlow = { nodes, edges };

export const ZONE_ANCHOR_IDS = [
  "qualidade_cana", "moagem_cana", "regeneradores", "aquecedores_caldo",
  "vapor_acucar", "vapor_destilaria", "fabrica_acucar", "producao_etanol",
  "producao_levedura", "eficiencias", "vapor", "bagaco", "energia_eletrica",
] as const;
